### ISSUE TITLE
Errors on isotope view

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#102]
Went to http://beta.jazkarta.com/projects/projects in Firefox and got error 1444581280.220.379025693559. (Same for /projects/projects/view) I believe @alecpm got an error on Chrome as well.

On Safari, http://beta.jazkarta.com/projects/projects/view or http://beta.jazkarta.com/projects/projects works. But if I shift-reload it all the thumbs stack on top of each other. This happened the very first time I went to the page too.

**Comment by skleinfeldt** [comment]
Also gets an error on iPad and iPhone.

**Comment by cewing** [comment]
This error is raised because some of the items in the projects collection have relationships with "services" that are not published.  I've made the isotope filtering system more robust against this possibility, and now if the name of a service cannot be looked up (because the item it comes from is private), it will be omitted from the list of available values to be used.

**Comment by cewing** [comment]
This is deployed (or will be in a few minutes, once opsworks finishes the job).  Sending to you to review.

**Comment by skleinfeldt** [comment]
Totally and completely awesome.
