### ISSUE TITLE
Isotope dropdown controls have dissappeared on staging

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#158]
They have become a dark rectangle above the first tile: https://staging.jazkarta.com/projects

I think this is new since the fixes you made yesterday @alecpm so beware deploying them to production until this is resolved.

**Comment by alecpm** [comment]
Looks like the isotope settings were erased during some registry settings import:

https://staging.jazkarta.com/@@collective-isotope-settings

I've put them back into place.

**Comment by alecpm** [comment]
The black bar is still there though. That appears to be the folder itself showing up in the search.

**Comment by alecpm** [comment]
There was an old homepage in the folder showing up. Making it private fixed the box.

**Comment by alecpm** [comment]
The changes were already all deployed to production. However, some changes (the mosaic tile styles) were for staging only. That's the only change that required an upgrade step (for the configuration registry), so I guess is sort of makes sense that it could have been what messed up the isotope config. However, looking at the registry changes, I'm completely baffled how those isotope settings would have been reset during any recent upgrade steps. My guess is the registry settings were wiped out in some earlier product upgrade/install, but the persisted config on the isotope content prevented it from showing up.

What seems most likely is that the old [home page Collection](https://staging.jazkarta.com/projects/projects), which had the configuration saved and continued working, was unset by someone as the default page. Then the `Isotope View` was applied to the folder in place of the content object. Since the folder itself had no previous isotope configuration set, the filters went away; and since the folder contained the old default Collection object, that showed up as the mysterious dark bar.

**Comment by alecpm** [comment]
Going with the view applied directly to the folder seems like a good choice for simplicity, as long as we restrict the published contents of the folder to projects only and store all projects directly in that folder.

**Comment by skleinfeldt** [comment]
Weird, I certainly didn't unset that collection of projects as the default page on purpose, and I can't image anyone else would have... I didn't notice that that had happened.

I'd rather continue to use the collection (with Isotope View applied) as the default page, because the collection sorts by reverse order of launch date and  then I don't want to have to worry about the ordering of the projects in the folder. So I set it back that way.

Thanks for re-doing the isotope registry settings, I'll try to remember to check that if it happens again.

**Comment by alecpm** [comment]
Just FYI, you can add sorting as an option to the isotope config and have it default to date sorting (though I don't think it would be reversed by default).

**Comment by skleinfeldt** [comment]
Good to know. (Although reverse sorting is good, and I don't think Launch Date is the same as published date.)

**Comment by alecpm** [comment]
Indeed, though if it's indexed we could add it to the isotope options. I'm not sure the sort UI was ever implemented though. It's configurable, but I'm not seeing UI for it.
