### ISSUE TITLE
Overlay text on top of sax homepage banner

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#173]
The text should be: " Extraordinary websites for non-profits and research institutions"

Leah says "The photo has a gradient of black going from left to right, and set to multiply for the header image".

Here is a rough mockup, this is probably about `H1` size but not all caps:

![homepage-sax-text-mockup](https://user-images.githubusercontent.com/1198463/90271878-833c9600-de2a-11ea-8e0f-f7bbfe9d5a80.png)

Note the alignment of the Logo, the overlaid text, and the body text/title, this would be ideal.

**Comment by alecpm** [comment]
This is up on staging.

**Comment by skleinfeldt** [comment]
Excellent. Looks great on desktop, a bit cramped on my iPhone 6:

![homepage-header](https://user-images.githubusercontent.com/1198463/91191228-82c1bc00-e6c2-11ea-883d-7d3f86e05302.PNG)

**Comment by alecpm** [comment]
I can reduce the font size a bit at that breakpoint, but I think you may have large fonts enabled on your device or something. It looks reasonable on all the other 375px wide devices and simulated devices I've tried (supposedly the iPhone 6 is that same width). I have a smaller breakpoint for iPhone SE and other smaller phones that uses an even smaller font, but I'm reluctant to reduce it at 375px because it looks pretty good on devices with normal font settings AFAICT, and I don't think it will look great much smaller than that.

![IMG_1299](https://user-images.githubusercontent.com/202854/91241499-dbf91200-e6f9-11ea-8440-09ef10ad7ec8.PNG)

**Comment by skleinfeldt** [comment]
I don't to my knowledge have large fonts enabled on my phone (how would I find out?) But this is definitely not worth futzing with further. Closing.
