### ISSUE TITLE
Increase border

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#34]
Increase the left and right border space. Double it around the header/footer, and increase it even more around the body. Similar to http://digital-loom.com.

**Comment by alecpm** [comment]
I'm not sure what you mean by left and right border space here.  Do you mean the padding around the body?  If so that's going to be a bit tricky with the way our responsiveness is being implemented, since the content area is a fixed width and the padding size depends on the browser width.  Basically there are three breakpoints based on browser width: 1200px, 992px, 768px

For those widths the content widths are fixed at: 1170px, 970px, 750px respectively

It might help to know what browser width you're viewing at.

We can increase the minimum effective padding by changing the difference between those corresponding widths.  Not sure whether we want to change the breakpoints or change the content widths, but probably the latter though things might start looking funny as you get further away from the initial break point and the padding gets really big.

**Comment by alecpm** [comment]
I've done what I think you wanted for the padding.  Let me know if it looks OK.

**Comment by skleinfeldt** [comment]
Yeah, this is hard to define precisely because of the responsive behavior. But what you did looks good to me!
