### ISSUE TITLE
Configure mailhost

### ISSUE THREAD

**Issue by davisagli** [jazkarta/jazkarta.com#42]

**Comment by skleinfeldt** [comment]
Current settings are: 

server: localhost 
port: 25 
from name: “Jazkarta Webmaster”  
from addr: webmaster@jazkarta.com

As David says "that’s not going to work on AWS, the EC2 ip ranges are on spam blocklists. we need to either send via a gmail account or via something like sendgrid or SES"

info@jazkarta.com is part of our google apps gmail setup, can we use that?

**Comment by davisagli** [comment]
Go to http://beta.jazkarta.com/@@mail-controlpanel and configure like this:

SMTP server: smtp.gmail.com
SMTP port: 587
ESMTP username: (gmail username)
ESMTP password (gmail password)

**Comment by skleinfeldt** [comment]
Assigning to @natea to do this.

**Comment by skleinfeldt** [comment]
@natea poke

**Comment by natea** [comment]
I don't seem to have a login to the beta.jazkarta.com site. I tried a password reset for all my usual usernames but all of them came up "The username you entered could not be found."

Could someone set up an admin account for me and then I can set up the Gmail account?

Is there any reason we wouldn't want to use a free Mandrill or Sendgrid account instead of relying on Gmail for this?

**Comment by cguardia** [comment]
Nate, please use admin account. Check Skype for password. Thanks.

**Comment by cguardia** [comment]
Thanks to @natea, this is set up.
