### ISSUE TITLE
HELP! Can't drag and drop content in cover compose

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#59]
Happens on front-page or homepage. 

Click Compose. 
Click Add Content. 
Click Content Tree
Click Services (to see those folders)
Drag one of the items to one of the Basic tiles

It drags but it will not drop. Worked fine when I tried it with Cris yesterday.

**Comment by skleinfeldt** [comment]
I just added a new cover page (http://beta.jazkarta.com/services/plone-websites/plone-websites/) and drag n drop worked fine. Removing blocker status, I can recreate the front-page layout pretty easily. But it would be nice to know how this happened so I can prevent it from happening again.

**Comment by skleinfeldt** [comment]
Putting back the blocker status. I just created a new cover, jazkarta-home-page, adjusted the layout, and when I went into compose I have the same problem, Add Content drag n drop doesn't work.

**Comment by skleinfeldt** [comment]
Created another cover, /services/services, and same problem. Also spinning wheel of death is getting out of control. I'm on FF, going to restart.

**Comment by cewing** [comment]
@skleinfeldt: I believe I may have figured out what is causing this problem to occur.

In the collective.cover control panel in site setup there is a setting called "Searchable Content Types".  It appears that not only does this setting control what types of content are shown in the search for content in the 'Add Content' panel, but it also controls what types of content are allowed to be dropped onto tiles like the basic tile.  

The current settings as of when I checked just now **do not** include the `Folder` type.  I updated the setting to include the `Folder` type, and now when I go to the `jazkarta-home-page` cover page I can successfully take the following steps:

1.  Click on "Compose"
2.  Click on "Add Content"
3.  Click on "Content Tree"
4.  Click on "Services" in the list of folders at the top of the site
5.  Drag and drop "Plone Websites" from the list of top-level folders in the `Services` Folder onto one of the basic tiles.

I think this is the solution to the problem.  Please verify that it works for you too, but I've tested both in FF and Chrome on my machine, and this appears to solve the issue.  The difference between before and after for you this weekend may well have been due to changes in that control panel instigated by some package update.

**Comment by skleinfeldt** [comment]
Hooooooray hooray! Thanks for figuring this out, and so glad it wasn't some obscure JS bug! I'll try to remember this for next time...
