### ISSUE TITLE
New footer

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#66]
Implement new footer styling. See new design. All text is white, no mouseover behavior. Fonts are a little different. Note that Jazkarta logo in the footer is the lighter Jazkarta blue (different from the header).

Tell me what additional information to ask Leah for.

**Comment by alecpm** [comment]
If the font is actually different, it would be helpful to know what the font is.  I'm assuming the footer logo is going to be placed in the portlet there rather than being incorporated into the theme?  It could just reference the existing logo file: /Plone/++theme++jazkarta.plonetheme/images/jazkarta_logo.png

Though I guess we might rename that if we add a white version.  Other than that I think these changes are in place.

**Comment by skleinfeldt** [comment]
Currently the headings (Get In Touch etc.) are the portlet titles, so putting logo in the body doesn't work. Also because the logo has a bit of space around it, I had to use the nbsp entity to adjust the text space, which doesn't seem so good.

Do you want me to stick with the self-service idea and move the portlet titles into the body? Or do you want to make this part of the theme?

**Comment by skleinfeldt** [comment]
Also as @davisagli noted on #78 , the first footer column is too far left.

**Comment by alecpm** [comment]
Ok, these issues are taken care of.

**Comment by skleinfeldt** [comment]
Excellent.
