### ISSUE TITLE
design comments

### ISSUE THREAD

**Issue by davisagli** [jazkarta/jazkarta.com#78]
A couple comments on the new design:

1. There's nothing above the fold that gives any indication what we do:

![screen shot 2015-09-23 at 7 41 53 pm](https://cloud.githubusercontent.com/assets/49014/10064237/3a2824e6-622b-11e5-8b93-bc4096242abd.png)

Maybe we can find a way to move the "Agile Process/Open Source platforms/Expert People" text up to be overlaid on the sax image? I think that text is a great summary of who we are and it's a shame to bury it.

2. I think the footer would look better if it had the same margin as the content area. Currently it looks like it's too far left.

**Comment by skleinfeldt** [comment]
Yes about the footer placement, although how to solve that is still under discussion.

I definitely see what you mean about the content-free above the fold problem. Leah and I debated the superimposed text idea - the problem was that she had to edit the sax image so it had a dark spot for the text to go on, and both of us preferred the brighter image. 

But we never tried overlaid text on the final sax image. I have created a homepage clone that has the text, http://beta.jazkarta.com/copy_of_front-page - could you please put the text back on top of the image  and make it white with the dark blue for the link? (Or it may be better all in white with no links - the links don't seem as critical for this use.) I agree we should revisit this.

**Comment by davisagli** [comment]
Ideas:
1. Put the text in a partially opaque dark box superimposed on the sax, so that we don't have to edit the image.
2. If we really don't want to obscure the image, crop enough off the top of it to gain space for a horizontal bar that contains the tagline text in a single line (could be above or below the sax, probably better below for visual balance)

**Comment by skleinfeldt** [comment]
Those are good suggestions. Will discuss with Leah.

**Comment by alecpm** [comment]
I've found that a little black drop shadow on does a pretty good job at highlighting light colored text overlaid on almost any image.  I'll give that a try.

**Comment by alecpm** [comment]
I've adjusted the footer width so it matches the body and not the header.  And have overlaid the text on the homepage image with a minimal drop shadow.  That image is pretty busy though, so the shadow can only do so much.  I could try increasing the shadow size or add a translucent box (rounded or squared and what color?).

**Comment by skleinfeldt** [comment]
I think that's pretty promising. I removed the links and pushed it down several lines, which helped. Substituted About for the now redundant text, but don't like that. Will continue to work on this.

**Comment by skleinfeldt** [comment]
I switched the homepage to the one with overlaid text - still needs some love but I'm convinced of the need. Closing this.
