### ISSUE TITLE
Styling for Isotope filters

### ISSUE THREAD

**Issue by skleinfeldt** [jazkarta/jazkarta.com#90]
Suggestions welcome, but given space considerations I think these need to be side by side dropdowns.

**Comment by cewing** [comment]
Switched out the button approach for the select2 mockup pattern.  Really much nicer.

**Comment by skleinfeldt** [comment]
Yes, much nicer! Couple tweaks:

- Remove the search box in the dropdown. I'm dubious this is a generally useful feature because I don't think the use cases for this functionality would include dozens of values you would want to search. But in any case we definitely don't need/want it on jaz.com.
- Make the dropdowns narrower so they fit 3 across.
- Selecting a value in one dropdown should not clear the value in the others. You should be able to filter for Plone non-profit projects for example.

**Comment by cewing** [comment]
The first bullet is easily accomplished.  The second one was already done, but for some reason you appear to be getting old css, so I've added a cache-busting querystring to the css in our theme.  That should fix it so that you get the right stuff

As for the third bullet point, that's a bit harder to do.  What should happen to values in the second, or third, or fourth search box if there are no items left that match them?  This will take a bit of effort to make "correct"

**Comment by cewing** [comment]
@skleinfeldt, when you arrive at the conference we can talk over the desired behavior for the third bullet point.

**Comment by skleinfeldt** [comment]
@cewing agreed, we can talk through this stuff tomorrow. (My thought was to show nothing if nothing matched. But that may be a bad idea.) 

On point 2 I see that I was below a responsive breakpoint.

I love this thing! Now if only the thumb cropping would work...

**Comment by skleinfeldt** [comment]
@cewing i tested the multiple filters thing and it works great! Thank you!
